  name: tests

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
      
  jobs:
    
    # build:
      
    #   runs-on: ubuntu-latest

    #   steps:
    #   - uses: actions/checkout@v2
    #   - uses: arduino/compile-sketches@v1
    #     with:
    #       sketch-paths: |
    #         - ./
    #       libraries: |
    #         - name: RF24

    coverage:
      
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      # install dependencies
      - name: conan
        run: |
          pip install conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: install
        run: conan install --install-folder build .
      - name: gcovr
        run: pip install gcovr
      - name: arduino-cli
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
      # build project
      - name: cmake generate
        run: cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D PORT=/dev/ttyACM0
      - name: configure arduino
        run: |
          export PATH=/home/runner/work/gridCar/gridCar/bin:$PATH
          cmake --build build --target configure
      - name: compile executable
        run: |
          export PATH=/home/runner/work/gridCar/gridCar/bin:$PATH
          arduino-cli board list
          cmake --build build --target compile
      - name: compile and run tests
        run: cmake --build build --target test
      # generate codecoverage report
      - name: create coverage report
        run: gcovr --xml=coverage.xml --txt -r .
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
